version: '3.4'

services:
  #catalog db info
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db 
  #catalog db info end 
  
  #basket db info
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
   
  #basket db info end 

   #discount db info
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  #discount db info end
  #sql order db 
  orderdb:
    container_name: orderdb
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5433:1433"
  #sql order db end

   #pgadmin info
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  #pgadmin info end

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #not local host but db container name catalogdb
    depends_on:
      - catalogdb   #first starts with catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379" 
      - "GrpcSettings:DiscountUrl=http://dicount.grpc" 
    depends_on:
      - basketdb   #first starts with catalogdb
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  dicount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678" 
    depends_on:
      - orderdb
    ports:
      - "8004:80"


  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:80"

