version: '3.4'

services:
  #catalog db info
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db 
  #catalog db info end 
  
  #basket db info
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
   
  #basket db info end 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #not local host but db container name catalogdb
    depends_on:
      - catalogdb   #first starts with catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379" 
    depends_on:
      - basketdb   #first starts with catalogdb
    ports:
      - "8001:80"

