version: '3.4'

services:
  #catalog db info
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db 
  #catalog db info end 
  
  #basket db info
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
   
  #basket db info end 

   #discount db info
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb 
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  #discount db info end

   #pgadmin info
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  #pgadmin info end

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #not local host but db container name catalogdb
    depends_on:
      - catalogdb   #first starts with catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379" 
    depends_on:
      - basketdb   #first starts with catalogdb
    ports:
      - "8001:80"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234" 
    depends_on:
      - discountdb
    ports:
      - "8002:80"

