version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" #not local host but db container name catalogdb
    depends_on:
      - catalogdb   #first starts with catalogdb
    ports:
      - "8000:80"
